# ClaudeCode Configuration - AI Engineering Platform
# Updated Configuration: Comprehensive AI Development Partner System
# Version: 2.0 - Enhanced with Advanced Methodologies

# Core AI Persona Configuration
persona:
  - agent-config/persona/professor_spark.md
  - agent-config/persona/prd_creation_agent.md
  - agent-config/persona/interaction_protocols.md

# Prompt Engineering Framework
prompts:
  - agent-config/prompts/prd_question_framework.md
  - agent-config/prompts/questions_framework.md
  - agent-config/prompts/task_list_interactions.md
  - agent-config/prompts/task_planning_phrases.md
  - agent-config/prompts/brainstorming_framework.md

# Development Guardrails & Quality Control
guardrails:
  - agent-config/guardrails/mode_behavior_control.md
  - agent-config/guardrails/no_code_generation.md
  - agent-config/guardrails/response_length_control.md
  - agent-config/guardrails/task_execution_protocol.md
  - agent-config/guardrails/require_confirmation_before_detail.md
  - agent-config/guardrails/use_tools_when_available.md
  - agent-config/guardrails/development_standards.md
  - agent-config/guardrails/testing_coverage_requirements.md

# Progress Continuity System
progress_continuity:
  - progress-state/MASTER_IMPLEMENTATION_PLAN.md
  - progress-state/PROGRESS_STATE.json
  - progress-state/SESSION_RESUME.md
  - progress-state/RESUME_COMMANDS.md
  - progress-state/CHECKPOINT_SYSTEM.md

# AI Behavior & Cognitive Management
behaviors:
  - agent-config/behaviors/framework_orchestration.md
  - agent-config/behaviors/tool_usage_prioritization.md
  - agent-config/behaviors/task_lifecycle.md
  - agent-config/behaviors/context_management.md
  - agent-config/behaviors/session_management.md

# Development Workflow Engine
workflows:
  - agent-config/workflows/00_project_initialization.md
  - agent-config/workflows/00_validate_dev_setup.md
  - agent-config/workflows/01_create_prd_from_idea.md
  - agent-config/workflows/02_generate_prd_file.md
  - agent-config/workflows/03_generate_task_list.md
  - agent-config/workflows/04_specs_driven_development.md
  - agent-config/workflows/05_test_driven_development.md
  - agent-config/workflows/06_github_integration.md

# Template & Code Generation Framework
templates:
  - agent-config/templates/task_list_skeleton.json
  - agent-config/templates/analysis_framework_selector.json
  - agent-config/templates/prd_structure_template.json
  - agent-config/templates/github_issue_template.json
  - agent-config/templates/spec_template.json
  - agent-config/templates/test_template.json

# Command Templates for AI Operations
command_templates:
  - agent-config/command_templates/do_task_template.md
  - agent-config/command_templates/planning_template.md
  - agent-config/command_templates/issue_creation_template.md
  - agent-config/command_templates/session_summary_template.md

# Dynamic Task Management
tasks:
  # Dynamically generated task files
  # Pattern: tasks/[type]-[project-name]-[timestamp].md
  # Examples:
  # - tasks/spec-user-profile-editing-20241201.md
  # - tasks/implementation-api-gateway-20241201.md
  # - tasks/testing-integration-suite-20241201.md

# Progress State Management
progress_state:
  enabled: true
  state_file: "progress-state/PROGRESS_STATE.json"
  checkpoint_frequency: 30
  auto_resume: true
  recovery_enabled: true

# Product Requirements Documentation
prd:
  - prd/PRD-professor_spark_subsystem.md
  # Additional PRDs generated dynamically
  # Pattern: prd/PRD-[project-name]-[version].md

# Feature Development Tracking
features:
  # Generated feature documentation and tracking
  # Pattern: features/[feature-name]-[status].md
  # Examples:
  # - features/user-authentication-active.md
  # - features/data-analytics-planned.md

# Session & Development Logs
logs:
  # Development session logs and progress tracking
  # Pattern: logs/session-[date]-[summary].md
  # Pattern: logs/decision-[date]-[context].md
  # Examples:
  # - logs/session-20241201-architecture-design.md
  # - logs/decision-20241201-database-selection.md

# AI Engineering Methodologies Integration
methodologies:
  specs_driven_development:
    enabled: true
    template: templates/spec_template.json
    workflow: workflows/04_specs_driven_development.md

  test_driven_development:
    enabled: true
    workflow: workflows/05_test_driven_development.md
    test_template: templates/test_template.json

  context_engineering:
    enabled: true
    behavior: behaviors/context_management.md
    cache_enabled: true

  github_integration:
    enabled: true
    workflow: workflows/06_github_integration.md
    issue_template: templates/github_issue_template.json

# System Configuration
system:
  version: "2.0"
  mode: "pro" # lite | standard | pro
  cache_enabled: true
  validation_enabled: true
  auto_documentation: true

# Quality Gates Configuration
quality_gates:
  pre_commit_required: true
  test_coverage_minimum: 80
  linting_required: true
  documentation_required: true
  spec_validation_required: true

# Integration Points
integrations:
  github:
    enabled: false # Set to true when GitHub token available
    repository_pattern: "organization/repository"
    issue_automation: true

  testing:
    framework: "pytest"
    coverage_tool: "pytest-cov"
    tdd_enforced: true

  documentation:
    auto_generation: true
    format: "markdown"
    api_docs: true

# Development Environment
environment:
  python:
    package_manager: "uv"
    version_minimum: "3.8"
    config_file: "pyproject.toml"

  git:
    pre_commit_enforced: true
    branch_protection: true
    commit_standards: true

  editor:
    config_file: ".editorconfig"
    extensions_recommended: true

# AI Command Registry
commands:
  # Analysis Commands
  analyze: "agent-config/workflows/04_specs_driven_development.md"
  plan: "agent-config/command_templates/planning_template.md"
  spec: "agent-config/templates/spec_template.json"

  # Development Commands
  tdd: "agent-config/workflows/05_test_driven_development.md"
  init: "agent-config/workflows/00_project_initialization.md"
  validate: "agent-config/workflows/00_validate_dev_setup.md"

  # Integration Commands
  github: "agent-config/workflows/06_github_integration.md"
  issue: "agent-config/templates/github_issue_template.json"
  pr: "agent-config/command_templates/pr_template.md"

  # Session Management
  start: "agent-config/behaviors/session_management.md"
  summary: "agent-config/command_templates/session_summary_template.md"
  context: "agent-config/behaviors/context_management.md"

  # Progress Continuity Commands
  resume_progress: "progress-state/RESUME_COMMANDS.md"
  checkpoint_save: "progress-state/CHECKPOINT_SYSTEM.md"
  progress_status: "progress-state/SESSION_RESUME.md"
  session_handoff: "progress-state/SESSION_RESUME.md"
  emergency_handoff: "progress-state/CHECKPOINT_SYSTEM.md"
  recover_from_checkpoint: "progress-state/CHECKPOINT_SYSTEM.md"
  analyze_blocker: "progress-state/RESUME_COMMANDS.md"

# Monitoring & Analytics
monitoring:
  session_tracking: true
  performance_metrics: true
  error_logging: true
  usage_analytics: true

# Security & Compliance
security:
  api_key_protection: true
  sensitive_data_filtering: true
  audit_logging: true
  access_control: true
